# ============================================
# MediScan AI - Application Properties
# ============================================

server.port=${PORT:8080}
# PostgreSQL Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Default Admin Credentials
admin.default.email=${ADMIN_EMAIL}
admin.default.password=${ADMIN_PASSWORD}
admin.default.name=System Admin
admin.default.role=ADMIN
admin.default.status=ACTIVE

## Firebase Configuration
#firebase.bucket-name=mediscan-ai.appspot.com
#firebase.config-path=firebase-service-account.json


cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# OCR Configuration
ocr.tessdata.path=C:/Program Files/Tesseract-OCR/tessdata
ocr.language=eng

## OpenAI / Spring AI Configuration
#spring.ai.openai.api-key=${OPENAI_API_KEY:sk-placeholder}
#spring.ai.openai.chat.options.model=gpt-4
#spring.ai.openai.chat.options.temperature=0.3

#google gemini api
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.3

# File Upload Limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# CORS
cors.allowed-origins=http://localhost:5173,http://localhost:3000

# Logging
logging.level.com.mediscan=DEBUG
logging.level.org.springframework.security=INFO



# Spring Mail (Gmail SMTP)

spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}

spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true



# ============================================
# Spring Mail (SMTP)
# ============================================

spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


# Google Calendar OAuth
google.client.id=${GOOGLE_CLIENT_ID}
google.client.secret=${GOOGLE_CLIENT_SECRET}
google.redirect.uri=http://localhost:8080/api/google/oauth/callback
